# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Storage X\About\Programirovanie\Python\Git\OverlayGT 2.0\main\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        Form.setMinimumSize(QtCore.QSize(1920, 1080))
        Form.setMaximumSize(QtCore.QSize(1920, 1080))
        self.f_main = QtWidgets.QFrame(Form)
        self.f_main.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.f_main.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.f_main.setObjectName("f_main")
        self.l_back_img = QtWidgets.QLabel(self.f_main)
        self.l_back_img.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.l_back_img.setScaledContents(True)
        self.l_back_img.setObjectName("l_back_img")
        self.f_child = QtWidgets.QFrame(Form)
        self.f_child.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.f_child.setObjectName("f_child")
        self.f_menu = QtWidgets.QFrame(self.f_child)
        self.f_menu.setGeometry(QtCore.QRect(845, 55, 230, 60))
        self.f_menu.setObjectName("f_menu")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.f_menu)
        self.hboxlayout.setContentsMargins(4, 4, 4, 4)
        self.hboxlayout.setSpacing(4)
        self.hboxlayout.setObjectName("hboxlayout")
        self.btn_mixer = MybtnMixer(self.f_menu)
        self.btn_mixer.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_mixer.setMaximumSize(QtCore.QSize(50, 50))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img_2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_mixer.setIcon(icon)
        self.btn_mixer.setIconSize(QtCore.QSize(20, 20))
        self.btn_mixer.setObjectName("btn_mixer")
        self.hboxlayout.addWidget(self.btn_mixer)
        self.btn_interpreter = QtWidgets.QPushButton(self.f_menu)
        self.btn_interpreter.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_interpreter.setMaximumSize(QtCore.QSize(50, 50))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img_1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_interpreter.setIcon(icon1)
        self.btn_interpreter.setIconSize(QtCore.QSize(25, 25))
        self.btn_interpreter.setObjectName("btn_interpreter")
        self.hboxlayout.addWidget(self.btn_interpreter)
        self.line = QtWidgets.QFrame(self.f_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setMaximumSize(QtCore.QSize(1, 52))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.hboxlayout.addWidget(self.line)
        self.l_time = QtWidgets.QLabel(self.f_menu)
        font = QtGui.QFont()
        font.setFamily("Biennale Black")
        font.setPointSize(14)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.l_time.setFont(font)
        self.l_time.setText("")
        self.l_time.setAlignment(QtCore.Qt.AlignCenter)
        self.l_time.setObjectName("l_time")
        self.hboxlayout.addWidget(self.l_time)
        self.btn_settings = QtWidgets.QPushButton(self.f_menu)
        self.btn_settings.setMinimumSize(QtCore.QSize(30, 50))
        self.btn_settings.setMaximumSize(QtCore.QSize(30, 50))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_settings.setIcon(icon2)
        self.btn_settings.setIconSize(QtCore.QSize(20, 20))
        self.btn_settings.setObjectName("btn_settings")
        self.hboxlayout.addWidget(self.btn_settings)
        self.AudioWidget = AudioWidget(self.f_child)
        self.AudioWidget.setGeometry(QtCore.QRect(390, 460, 320, 420))
        self.AudioWidget.setObjectName("AudioWidget")
        self.TranslitWidget = TranslitWidget(self.f_child)
        self.TranslitWidget.setGeometry(QtCore.QRect(460, 200, 505, 255))
        self.TranslitWidget.setObjectName("TranslitWidget")
        self.SettingsWidget = SettingsWidget(self.f_child)
        self.SettingsWidget.setGeometry(QtCore.QRect(1090, 480, 480, 340))
        self.SettingsWidget.setObjectName("SettingsWidget")
        self.StatsWidget = StatsWidget(self.f_child)
        self.StatsWidget.setGeometry(QtCore.QRect(0, 1010, 130, 70))
        self.StatsWidget.setObjectName("StatsWidget")
        self.MusicWidget = MusicWidget(self.f_child)
        self.MusicWidget.setGeometry(QtCore.QRect(725, 120, 300, 80))
        self.MusicWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.MusicWidget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.MusicWidget.setObjectName("MusicWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        pass
from modified_elements.btn_mixer import MybtnMixer
from widgets.audio_widget import AudioWidget
from widgets.music_widget import MusicWidget
from widgets.settings_widget import SettingsWidget
from widgets.stats_widget import StatsWidget
from widgets.translit_widget import TranslitWidget
