# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Storage X\About\Programirovanie\Python\Git\OverlayGT 2.0\main\ui\widget_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_StatsWidget(object):
    def setupUi(self, StatsWidget):
        StatsWidget.setObjectName("StatsWidget")
        StatsWidget.resize(122, 69)
        StatsWidget.setStyleSheet("color: rgb(255, 255, 255);")
        self.vboxlayout = QtWidgets.QVBoxLayout(StatsWidget)
        self.vboxlayout.setContentsMargins(5, 30, 5, 0)
        self.vboxlayout.setSpacing(0)
        self.vboxlayout.setObjectName("vboxlayout")
        self.l_stat = QtWidgets.QLabel(StatsWidget)
        self.l_stat.setObjectName("l_stat")
        self.vboxlayout.addWidget(self.l_stat)
        self.l_stat_1 = QtWidgets.QLabel(StatsWidget)
        self.l_stat_1.setObjectName("l_stat_1")
        self.vboxlayout.addWidget(self.l_stat_1)
        self.l_stat_2 = QtWidgets.QLabel(StatsWidget)
        self.l_stat_2.setObjectName("l_stat_2")
        self.vboxlayout.addWidget(self.l_stat_2)

        self.retranslateUi(StatsWidget)
        QtCore.QMetaObject.connectSlotsByName(StatsWidget)

    def retranslateUi(self, StatsWidget):
        pass
