# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Storage X\About\Programirovanie\Python\Git\OverlayGT 2.0\main\ui\widget_4.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MusicWidget(object):
    def setupUi(self, MusicWidget):
        MusicWidget.setObjectName("MusicWidget")
        MusicWidget.resize(300, 80)
        MusicWidget.setMinimumSize(QtCore.QSize(300, 80))
        MusicWidget.setMaximumSize(QtCore.QSize(300, 80))
        self.hL = QtWidgets.QHBoxLayout(MusicWidget)
        self.hL.setContentsMargins(10, 10, 10, 10)
        self.hL.setSpacing(5)
        self.hL.setObjectName("hL")
        self.btn_prev = QtWidgets.QPushButton(MusicWidget)
        self.btn_prev.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_prev.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_prev.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/img_14.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_prev.setIcon(icon)
        self.btn_prev.setIconSize(QtCore.QSize(25, 25))
        self.btn_prev.setObjectName("btn_prev")
        self.hL.addWidget(self.btn_prev)
        self.btn_pp = QtWidgets.QPushButton(MusicWidget)
        self.btn_pp.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_pp.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_pp.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/img_12.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_pp.setIcon(icon1)
        self.btn_pp.setIconSize(QtCore.QSize(25, 25))
        self.btn_pp.setObjectName("btn_pp")
        self.hL.addWidget(self.btn_pp)
        self.btn_next = QtWidgets.QPushButton(MusicWidget)
        self.btn_next.setMinimumSize(QtCore.QSize(50, 50))
        self.btn_next.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_next.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/img_13.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_next.setIcon(icon2)
        self.btn_next.setIconSize(QtCore.QSize(25, 25))
        self.btn_next.setObjectName("btn_next")
        self.hL.addWidget(self.btn_next)

        self.retranslateUi(MusicWidget)
        QtCore.QMetaObject.connectSlotsByName(MusicWidget)

    def retranslateUi(self, MusicWidget):
        pass
